// Last updated: March 2023

import { ClipboardAPI } from './clipboard';
import { LocalFilesAPI } from './local-files';
import { PlayerAPI } from './player';
import { PlaylistAPI } from './playlist';
import { RootlistAPI } from './rootlist';
import { Session } from './session';
import { Translations } from './translations';
import { UserAPI } from './user';
import { History } from './history';
import { ShowAPI } from './show';
import { LocalStorageAPI } from './local-storage';

export type Platform = {
    Session: Session;
    Transport: unknown;
    EventSender: unknown;
    Translations: Translations;
    FeatureFlags: unknown;
    History: History;
    AdManagers: unknown;
    RemoteConfiguration: unknown;
    ActionStoreAPI: unknown;
    AuthorizationAPI: unknown;
    ClipboardAPI: ClipboardAPI;
    ConnectAPI: unknown;
    SocialConnectAPI: unknown;
    ControlMessageAPI: unknown;
    FacebookAPI: unknown;
    FollowAPI: unknown;
    GraphQLLoader: unknown;
    LibraryAPI: unknown;
    LocalFilesAPI: LocalFilesAPI;
    OfflineAPI: unknown;
    PlatformData: unknown;
    PlayerAPI: PlayerAPI;
    ShuffleAPI: unknown;
    PlayHistoryAPI: unknown;
    PlaylistAPI: PlaylistAPI;
    PlaylistPermissionsAPI: unknown;
    PrivateSessionAPI: unknown;
    RadioStationAPI: unknown;
    RecaptchaLoggerAPI: unknown;
    RecentlyPlayedAPI: unknown;
    ReportAPI: unknown;
    RootlistAPI: RootlistAPI;
    SegmentsAPI: unknown;
    ShowAPI: ShowAPI;
    AudiobooksPremiumConsumptionCapObserverAPI: unknown;
    UpdateAPI: unknown;
    UserAPI: UserAPI;
    VideoAPI: unknown;
    EnhanceAPI: unknown;
    SEOExperiments: unknown;
    SingAlongAPI: unknown;
    PlaybackAPI: unknown;
    UBILogger: unknown;
    CollectionPlatformAPI: unknown;
    LocalStorageAPI: LocalStorageAPI;
    IndexedDbAPI: unknown;
    EqualizerAPI: unknown;
    BuddyFeedAPI: unknown;
    PanelAP: unknown;
};
